#!/bin/sh

#cleanup
rm -rf obj_dir
rm -f *.vcd

#run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace InstrMem.sv --exe MemTest.cpp

#build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f VInstrMem.mk VInstrMem

#run executable simulation file
obj_dir/VInstrMem